name: Build Maven Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.14
        with:
          jdk-version: ${{ inputs.java-version }}
          jdk-distribution: ${{ inputs.java-distribution }}
          mvn-args: ${{ inputs.mvn-args }}

  test-coverage:
    runs-on: ubuntu-20.04
    if: ${{ !inputs.ignore-coverage }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.14
        with:
          jdk-version: ${{ inputs.java-version }}
          jdk-distribution: ${{ inputs.java-distribution }}
          mvn-args: ${{ inputs.mvn-args }}

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        
      - name: Install and set up RevoluteBot
        uses: revolut-engineering/revolutebot@v1.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GitHub Security Code Scanning
        uses: github/codeql-action/analyze@v1
        with:
          languages: java
          sarif_file: ./codeql_results.sarif

      - name: Check for vulnerabilities from CodeQL or RevoluteBot
        run: |
          error_msg=""
          if [ -f ./codeql_results.sarif ] && grep -q '\"ruleId\": \"Security/\"' ./codeql_results.sarif; then
            error_msg="Security vulnerabilities detected by CodeQL.\n"
            codeql_output=$(cat ./codeql_results.sarif | jq '.runs[].results[] | select(.rule.id | startswith("Security/")) | "\(.rule.id): \(.message)"')
            error_msg="$error_msg$codeql_output\n"
          fi
          if [ -f ./revolutebot_issues.txt ]; then
            error_msg="$error_msg Outdated or vulnerable dependencies detected by Revolute
