name: Build Maven Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.14
        with:
          jdk-version: ${{ inputs.java-version }}
          jdk-distribution: ${{ inputs.java-distribution }}
          mvn-args: ${{ inputs.mvn-args }}

  test-coverage:
    runs-on: ubuntu-20.04
    if: ${{ !inputs.ignore-coverage }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.14
        with:
          jdk-version: ${{ inputs.java-version }}
          jdk-distribution: ${{ inputs.java-distribution }}
          mvn-args: ${{ inputs.mvn-args }}

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
